import type { Metadata } from "next";
// import "./globals.css"
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <div className="pt-0 lg:pt-10">{children}</div>
      </body>
    </html>
  );
}
